---
title: "PSY 8960 Final Project - Part 4"
author: "Saron Demeke"
date: "`r Sys.Date()`"
output: 
  html_document:
    df_print: paged
knit: (function(input, ...) { 
        rmarkdown::render(input, output_file='../markdown/final_dashboard.html') })
---
  
# Script Settings and Resources
```{r section1, message=F}
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
library(tidyverse)
```  
  

# Data Import and Cleaning
```{r section2}
full_dat <- read_rds("../rds/combined_dataset.rds")

skinny_dat <- full_dat %>% 
  select(EmployeeID, MonthlyIncome, Attrition, JobSatisfaction,
         Department, EducationField, Gender, JobRole) %>% 
   saveRDS("../shiny/people_dashboard/final_shiny_dat.RDS")


```



In console 
> library(rsconnect)
> rsconnect::setAccountInfo(name='sdemeke', token='74B7FDE39775CF5443EF9C632829F3DA', secret='0gmweLocppD0paHwx8WbIDkX40YHsvLbu3UraWaI')
> getwd()
[1] "C:/Users/demek004/Documents/SP23_PSY8960_DataScience/psy8960-final/R"
> deployApp("../shiny/people_dashboard")
